idea_factory/config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello/" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get  "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  resources :ideas do
    get   :search,    on: :collection
    patch :mark_done, on: :member
    post  :approve

    resources :comments, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

    resources :members, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  resources :members, only: [:index]

  resources :comments, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "ideas#index"

end

idea_factory/app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  def index
    # This renders the app/views/welcome/about.html.erb template
    # with no layout
    # render "/welcome/about", layout: false
  end

  def create
    render text: params
  end
end

idea_factory/app/helpers/subscribe_helper.rb
module SubscribeHelper
end

idea_factory/app/views/subscribe/index.html.erb
<div class="container">
  <h1>Subscirbe to Our Newsletter</h1>

<%# form_tag is a built-in Rails view helper that enables us to generate a form
    the first argument is the `action` attribute of the form. You can provide
    method: attribute to make the form use any type of request including: GET
    POST, PATCH and DELETE %>
<%= form_tag subscribe_path, method: :post do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name, nil, class:"form-control" %>
  </div>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email, nil, class:"form-control" %>
  </div>
  <%= submit_tag "Subscribe Now!", class:"btn btn-default" %>
<% end %>

</div>