idea_factory/config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello/" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get  "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  resources :ideas do
    get   :search,    on: :collection
    patch :mark_done, on: :member
    post  :approve

    resources :comments, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

    resources :members, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  resources :members, only: [:index]

  resources :comments, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "ideas#index"

end

idea_factory/app/views/layouts/application.html.erb
<%# this will be used as a default layout. %>
<!DOCTYPE html>
<html>
<head>
  <title>Idea Factory</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%#= image_tag "red_panda" %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <a class="navbar-left" href="<%= root_path %>"><%= image_tag "logo", class:"logo" %></a>
      <a class="navbar-brand navbar-left" href="<%= root_path %>">Idea Factory</a>

      <ul class="nav navbar-nav navbar-right">
        <!--li><a href="<%= about_path %>">About</a></li>
        <li><a href="<%= greet_path('John') %>"> Greet John </a></li>
        <li><%= link_to "Hello", hello_path %></li>
        <li><%= link_to "New Idea", new_idea_path %></li>
        <li><%= link_to "All Ideas", ideas_path %></li-->

        <% if session[:user_id] %>
          <li><a href="#">Hello <%= current_user.first_name %></a></li>
          <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
          <br>
          <li class="pull-right"><%= button_to "New Idea", new_idea_path, class:"btn btn-default", method: :get %></li>
        <% else %>
          <li><%= link_to "Login", new_session_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

<!-- <a href="/hello">Hello</a> |
<a href="/about">About</a> | -->
<%# hello_path & about_path are called route helpers. They get generated from
    the content of `routes.rb` and they are methods that can be used in
    all view files and all controllers %>
<!--
  <a href="<%= about_path %>">About</a> |
  <a href="<%= greet_path('John') %>"> Greet John </a> |

  <%= link_to "Hello", hello_path %> |
  <%= link_to "New Idea", new_idea_path %> |
  <%= link_to "All Ideas", ideas_path %> |

  <% if session[:user_id] %>
    Hello <%= current_user.first_name %>
    <%= link_to "Log out", sessions_path, method: :delete %></li>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
-->

<!-- <a href="<%= about_path %>">About</a> | -->
<!-- <a href="<%= greet_path({name: 'John'}) %>"> Greet John </a> -->
<!-- <a href="<%= greet_path('John') %>"> Greet John </a> | -->

<%# link_to is a helper method that is built-in with Rails, it's a view helper
    method, meaning it's accessible only in the views / view helpers. link_to
    takes a first argument which is the anchor text and a second argument which
    is the `href` value (url/path). It can take other options as we will see
    later. More info here:
    http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to %>






<%#= flash[:notice] || flash[:alert] %>

<%#= notice || alert %>

<% if notice %>
  <div class="alert alert-success alert-dismissible">
    <strong><%= notice %></strong>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible">
    <strong><%= alert %></strong>
  </div>
<% end %>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>