idea_factory/config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello/" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get  "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  resources :ideas do
    get   :search,    on: :collection
    patch :mark_done, on: :member
    post  :approve

    resources :comments, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

    resources :members, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  resources :members, only: [:index]

  resources :comments, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "ideas#index"

end

idea_factory/app/views/questions/index.html.erb
<div class="container">
  <h1>All Ideas (<%= @ideas.length %>)</h1>
  <!-- don't do this anymore -->
  <!-- <img src="/red_panda.jpg" /> -->
  <!-- start doing this now -->
  <%#= image_tag "red_panda.jpg" %>


  <table class="table table-striped">

    <% @ideas.each do |idea| %>

      <tr>
        <td>
          <%#= link_to idea.title, idea_path(idea) %>
          <h4><%= idea.title %><br></h4>
          <p><%= idea.body %><br><p>
          <p>By <%= link_to idea.user_full_name, idea_path(idea) %>
          <!-- <%= link_to "Join", new_idea_path, class:"btn btn-default" %>
          <%= link_to "Like", new_idea_path, class:"btn btn-default" %> -->
          <!-- <% if session[:user_id] == current_user %> -->



          <!-- <% end %> -->
        <% if cannot? :edit, idea %>
          <% member = idea.member_for(current_user) %>
          <% if member %>
            <!-- <%= link_to "Joined", new_idea_path, class:"btn btn-default" %> -->
            <%= link_to "Joined", idea_member_path(idea, member), method: :delete, class: "btn btn-default" %>
            <!-- <%= link_to fa_icon("heart"), idea_member_path(idea, member), method: :delete, class: "like-member-icon" %> -->
          <% else %>
            <!-- <%= link_to "Join", new_idea_path, class:"btn btn-default" %> -->
            <%= link_to "Join", idea_members_path(idea), method: :post, class: "btn btn-default" %>
            <!-- <%= link_to fa_icon("heart-o"), idea_members_path(idea), method: :post, class: "like-member-icon" %> -->
          <% end %>


          <% like = idea.like_for(current_user) %>
          <% if like %>
            <!-- <%= link_to "Liked", new_idea_path, class:"btn btn-default" %> -->
            <!-- <%= link_to fa_icon("thumbs-up"), idea_like_path(idea, like), method: :delete, class: "like-member-icon"  %> -->
            <%= link_to "Liked", idea_like_path(idea, like), method: :delete, class: "btn btn-default"  %>
          <% else %>
            <!-- <%= link_to "Like", new_idea_path, class:"btn btn-default" %> -->
            <!-- <%= link_to fa_icon("thumbs-o-up"), idea_likes_path(idea), method: :post, class: "like-member-icon" %> -->
            <%= link_to "Like", idea_likes_path(idea), method: :post, class: "btn btn-default" %>
          <% end %>
        <% end %>

          <span class="pull-right">Members: <span class="badge"><%= idea.members.count %></span> |
          Likes: <span class="badge"><%= idea.likes.count %></span></span></p>
        </td>
      </tr>
    <% end %>
  </table>
</div>

idea_factory/app/views/questions/show.html.erb
<!-- idea -->
<div class="container">
  <h1><%= @idea.title %></h1>
  <div class="col-sm-9 col-xs-12">
    <p><%= @idea.body %></p>




    <%# vote = @idea.vote_for(current_user) %>

    <%# if !vote %>
      <%#= link_to "Vote Up", idea_votes_path(@idea, {vote: {is_up: true}}),
                              method: :post %>
      <!-- (<%#= @idea.vote_result %>) -->
      <%#= link_to "Vote Down", idea_votes_path(@idea, {vote: {is_up: false}}),
                              method: :post %>
    <%# elsif vote.is_up? %>
      <%#= link_to "Remove Vote Up", idea_vote_path(@idea, vote),
                              method: :delete %>
      <!-- (<%#= @idea.vote_result %>) -->
      <%#= link_to "Vote Down", idea_vote_path(@idea, vote, {vote: {is_up: false}}),
                              method: :patch %>
    <%# else %>
      <%#= link_to "Vote Up", idea_vote_path(@idea, vote, {vote: {is_up: true}}),
                            method: :patch %>
      <!-- (<%#= @idea.vote_result %>) -->
      <%#= link_to "Remove Vote Down", idea_vote_path(@idea, vote),
                            method: :delete %>

    <%# end %>


<!--  stars & progress bar -->
<!--div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="70"
  aria-valuemin="0" aria-valuemax="100" style="width:70%">
    <span class="sr-only">70% Complete</span>
  </div>
</div-->

<!--label for="input-1" class="control-label">Rate This</label>
<input id="input-1" class="rating rating-loading" data-min="0" data-max="5" data-step="1"-->

    <!--hr-->
    <br><br>
    <div class="btn-group">
    <% if can? :edit, @idea %>
      <%= link_to "Edit", edit_idea_path(@idea), class:"btn btn-default btn-sm" %>
    <% end %>

    <% if can? :destroy, @idea %>
      <%#  method: :delete asks Rails to send a DELETE request instead of GET which
          is accomplished using Javascript/jQuery %>
      <%= link_to "Delete",
                  idea_path(@idea),
                  method: :delete,
                  data: {confirm: "Are you sure?"},
                  class:"btn btn-default btn-sm" %>
    <% end %>

    </div>
    <hr>
  </div>

<!-- info box -->
  <div class="col-md-3 col-sm-6 col-xs-12">
    <ul class="list-group">
      <li class="list-group-item">View Count:
        <span class="badge"><%= @idea.view_count %></span>
      </li>
      <li class="list-group-item"><%= @idea.created_at %></li>
      <li class="list-group-item">Created By: <%= @idea.user_full_name %></li>
      <li class="list-group-item">Likes: <span class="badge"><%= @idea.likes.count %></span></li>
      <li class="list-group-item">Members: <span class="badge"><%= @idea.members.count %></span>
        <br><br>
        <% @idea.membering_users.each do |member| %>
          <%= member.first_name + " " + member.last_name %>
        <% end %>
        <br>
      </li>
      </ul>
  </div>



<!-- comment -->
</div>
  <div class="container">
    <%# This is the like object for the `current_user` and `@idea` %>
    <h2>Comments</h2>
    <p>Add a Comment</p>
<%# we can use the form after overriding the `url` parameter. The downside to it
    is that it won't work for `edit` situation. This will only work in `create`
    situation. So we can't reuse it we decide to implement editing comments.%>
<%#= form_for @comment, url: idea_comments_path(@idea) do |f| %>
<%# end %>

    <%= @comment.errors.full_messages.join(", ") %>
<%# passing an array to the `form_for` is a better approach for creating nested
    resources. This approach will work for both new / edit sitatuions. So if
    @comment is not persisted it will send a POST request to
    idea_comments_path(@idea). And if @comment is persisted it will send
    a PATCH request to idea_comment_path(@idea, @comment) %>
    <%= form_for [@idea, @comment] do |f| %>
    <div>
      <%= f.text_area :body, class:"form-control" %>
    </div>
  <%= f.submit "Add Comment", class:"btn btn-default" %>
<% end %>

    <br><br>
    <table class="table table-striped">
<% @idea.comments.each do |ans| %>
    <tr>
      <td>
  <%= ans.body %> (by: <%= ans.user_full_name %>)
  <% if can? :destroy, ans %>
    <%= link_to "Delete", idea_comment_path(@idea, ans),
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                        class: "btn btn-default btn-sm" %>
  <% end %>
      </td>
    </tr>
<% end %>
  </div>